name: PHP Composer

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.3

      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Lint *.php files with PHP
        run: composer test:php:lint

      - name: Lint TypoScript files
        run: composer test:ts:lint

      - name: Run PHP-CS-FIXER
        run: composer cs:fix -- --dry-run

      - name: Run PHPStan
        run: composer cs:analyze
